# Generated by Django 4.2.6 on 2023-11-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_books_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='review',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
