# Generated by Django 4.2.6 on 2023-11-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_books_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='books',
            name='review',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
